###################################################################################################
# ██▀███   ▄▄▄      ███▄    █ ▓█████▄  ▒█████   ███▄ ▄███▓ ▄████▄  ▄▄▄      ██▀███  ▄▄▄█████▓     #
# ▓██ ▒ ██▒▒████▄    ██ ▀█   █ ▒██▀ ██▌▒██▒  ██▒▓██▒▀█▀ ██▒▒██▀ ▀█ ▒████▄   ▓██ ▒ ██▒▓  ██▒ ▓▒    #
# ▓██ ░▄█ ▒▒██  ▀█▄ ▓██  ▀█ ██▒░██   █▌▒██░  ██▒▓██    ▓██░▒▓█    ▄▒██  ▀█▄ ▓██ ░▄█ ▒▒ ▓██░ ▒░    #
# ▒██▀▀█▄  ░██▄▄▄▄██▓██▒  ▐▌██▒░▓█▄   ▌▒██   ██░▒██    ▒██ ▒▓▓▄ ▄██░██▄▄▄▄██▒██▀▀█▄  ░ ▓██▓ ░     #
# ░██▓ ▒██▒▒▓█   ▓██▒██░   ▓██░░▒████▓ ░ ████▓▒░▒██▒   ░██▒▒ ▓███▀ ▒▓█   ▓██░██▓ ▒██▒  ▒██▒ ░     #
# ░ ▒▓ ░▒▓░░▒▒   ▓▒█░ ▒░   ▒ ▒  ▒▒▓  ▒ ░ ▒░▒░▒░ ░ ▒░   ░  ░░ ░▒ ▒  ░▒▒   ▓▒█░ ▒▓ ░▒▓░  ▒ ░░       #
# ░▒ ░ ▒░░ ░   ▒▒ ░ ░░   ░ ▒░ ░ ▒  ▒   ░ ▒ ▒░ ░  ░      ░  ░  ▒  ░ ░   ▒▒   ░▒ ░ ▒     ░          #
# ░   ░   ░   ▒     ░   ░ ░  ░ ░  ░ ░ ░ ░ ▒  ░      ░   ░         ░   ▒    ░░   ░   ░             #
# ░           ░           ░    ░        ░ ░         ░   ░ ░           ░     ░                     #
###################################################################################################

# This file handles the configuration for the RandomCart Minecraft plugin.
# Once you have understood the configuration, feel free to delete the comments, I know there's a lot.
# Plugin created by Triassic.


randomcart:
  chance: 0.5 # The chance that a RandomCart spawns.
  # Blocks that have the ability to spawn RandomCarts.
  allowed-blocks:
    - STONE
    - DIRT
    - GRASS_BLOCK

minecarts:
#  miner-cart: # Identifier used internally by the plugin.
#    name: "&9Miner's Cart" # Displayed in the Minecart's Chest GUI as the title.
#    # List of items that will be included in this preset.
#    items:
#      0: # Slot the item should be added in. Slots begin from 0.
#        material: "IRON_PICKAXE" # The Item Name.
#        display-name: "&fMiner's Pickaxe" # The Name of the item displayed to players.
#        # Lore of the Item displayed to players.
#        lore:
#          - "&7From the deepest depths of the caves."
#        # Item Enchantments
#        enchantments:
#          EFFICIENCY: # Enchantment Name.
#            level: 4 # Enchantment Level.
#      1:
#        material: "STONE"
#        display-name: "&dSpecial Stone"
#        lore:
#          - "&7I don't know why!"
#        amount: 64
#      2:
#        material: "STONE_BRICKS"
#        amount: 64
#      3:
#        material: "COOKED_PORKCHOP"
#        amount: 16
#      4:
#        material: "COBBLESTONE"


version: 1.0.2 # DO NOT MODIFY.