###################################################################################################
# ██▀███   ▄▄▄      ███▄    █ ▓█████▄  ▒█████   ███▄ ▄███▓ ▄████▄  ▄▄▄      ██▀███  ▄▄▄█████▓     #
# ▓██ ▒ ██▒▒████▄    ██ ▀█   █ ▒██▀ ██▌▒██▒  ██▒▓██▒▀█▀ ██▒▒██▀ ▀█ ▒████▄   ▓██ ▒ ██▒▓  ██▒ ▓▒    #
# ▓██ ░▄█ ▒▒██  ▀█▄ ▓██  ▀█ ██▒░██   █▌▒██░  ██▒▓██    ▓██░▒▓█    ▄▒██  ▀█▄ ▓██ ░▄█ ▒▒ ▓██░ ▒░    #
# ▒██▀▀█▄  ░██▄▄▄▄██▓██▒  ▐▌██▒░▓█▄   ▌▒██   ██░▒██    ▒██ ▒▓▓▄ ▄██░██▄▄▄▄██▒██▀▀█▄  ░ ▓██▓ ░     #
# ░██▓ ▒██▒▒▓█   ▓██▒██░   ▓██░░▒████▓ ░ ████▓▒░▒██▒   ░██▒▒ ▓███▀ ▒▓█   ▓██░██▓ ▒██▒  ▒██▒ ░     #
# ░ ▒▓ ░▒▓░░▒▒   ▓▒█░ ▒░   ▒ ▒  ▒▒▓  ▒ ░ ▒░▒░▒░ ░ ▒░   ░  ░░ ░▒ ▒  ░▒▒   ▓▒█░ ▒▓ ░▒▓░  ▒ ░░       #
# ░▒ ░ ▒░░ ░   ▒▒ ░ ░░   ░ ▒░ ░ ▒  ▒   ░ ▒ ▒░ ░  ░      ░  ░  ▒  ░ ░   ▒▒   ░▒ ░ ▒     ░          #
# ░   ░   ░   ▒     ░   ░ ░  ░ ░  ░ ░ ░ ░ ▒  ░      ░   ░         ░   ▒    ░░   ░   ░             #
# ░           ░           ░    ░        ░ ░         ░   ░ ░           ░     ░                     #
###################################################################################################

# This file handles the configuration for the RandomCart Minecraft plugin.
# Once you have understood the configuration, feel free to delete the comments, I know there's a lot.
# Plugin created by Triassic.


randomcart:
  chance: 0.5 # The chance that a RandomCart spawns.
  # Blocks that have the ability to spawn RandomCarts.
  allowed-blocks: []

minecarts:
#  miner-cart: # Identifier used internally by the plugin.
#    name: "&9Miner's Cart" # Displayed in the Minecart's Chest GUI as the title.
#    # List of items that will be included in this preset.
#    items:
#      IRON_PICKAXE: # Item Name.
#        display-name: "&fMiner's Pickaxe" # The Name of the item displayed to players.
#        amount: 1 # Amount of the item to add.
#        # Lore of the Item displayed to players.
#        lore:
#          - "&7From the deepest depths of the caves."
#        # Item Enchantments
#        enchantments:
#          EFFICIENCY: # Enchantment Name
#            level: 4 # Enchantment Level
#      STONE:
#        amount: 192
#      STONE_BRICKS:
#        amount: 128
#      COOKED_PORKCHOP:
#        amount: 16
#      COBBLESTONE: []


version: 1.0.1 # DO NOT MODIFY.